# Add 'core' label to any changes in the main integration code
core:
  - changed-files:
      - any-glob-to-any-file: 'custom_components/foodsharing/**/*.py'

# Add 'docs' label to any changes in documentation
docs:
  - changed-files:
      - any-glob-to-any-file: 'README.md'
      - any-glob-to-any-file: 'images/**/*'

# Add 'translation' label to any translation updates
translation:
  - changed-files:
      - any-glob-to-any-file: 'custom_components/foodsharing/translations/**/*'

# Add 'tests' label to any changes in the test suite
tests:
  - changed-files:
      - any-glob-to-any-file: 'tests/**/*'
      - any-glob-to-any-file: 'pytest.ini'
      - any-glob-to-any-file: 'requirements_test.txt'

# Add 'dependencies' label if requirement files change
dependencies:
  - changed-files:
      - any-glob-to-any-file: 'requirements.txt'
      - any-glob-to-any-file: 'hacs.json'

# Add 'workflows' label if GitHub actions change
workflows:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/**/*'
