DOMAIN = "foodsharing"
ATTRIBUTION = "Data provided by foodsharing.de api"

ATTR_BASKETS = "baskets"
ATTR_ID = "id"
ATTR_DESCRIPTION = "description"
ATTR_UNTIL = "available_until"
ATTR_PICTURE = "picture"
ATTR_ADDRESS = "address"
ATTR_LATITUDE = "latitude"
ATTR_LONGITUDE = "longitude"
ATTR_MAPS_LINK = "maps"

CONF_EMAIL = "email"
CONF_PASSWORD = "password"
CONF_LATITUDE_FS = "latitude"
CONF_LONGITUDE_FS = "longitude"
CONF_DISTANCE = "distance"
CONF_SCAN_INTERVAL = "scan_interval"