DOMAIN = "foodsharing"
ATTRIBUTION = "Data provided by foodsharing.de api"

ATTR_BASKETS = "baskets"
ATTR_ID = "id"
ATTR_DESCRIPTION = "description"
ATTR_UNTIL = "available until"
ATTR_PICTURE = "picture"

CONF_EMAIL = "Foodsharing.de E-Mail Adress"
CONF_PASSWORD = "Foodsharing.de Password"
CONF_LATITUDE_FS = "Latitude Coordinate"
CONF_LONGITUDE_FS = "Longitude Coordinate"
CONF_DISTANCE = "Distance in km"
#CONF_SCAN_INTERVAL = "Scan interval in minutes"